### ISSUE TITLE
images in the same directory

### ISSUE THREAD

**Issue by laszewsk** [cybertraining-dsc/fa20-523-313#3]
images in the same directory must not be unique and not have .png and .PNG ending.

Please remove .PNG files.

**Comment by laszewsk** [comment]
all PNG images were moved to the directory ./broken

You are not allowed to check-in .PNG and .JPG images into our github. please remove them to avoid confusion (e.g. ending must be lowercase)

**Comment by fauzanmursyid** [comment]
I'm sorry about that. When I use snipping tool it saved the image automatically in .PNG format, so I uploaded them in the wrong format. Thank you for moving the images. I also have re-uploaded the image that has the wrong format.

**Comment by laszewsk** [comment]
I propose you delete all .PNG images if they already exist in .png so that confusion is avoided.

The issue is that some systems that create the web page do not distinguish between lower and uppercase so the file name.png and name.PNG is the same. As they are in the same directory the compilation of your report than fails. I corrected this in the past, but you reuploaded .PNG files

once you deleted all .PNG files in /broken please close this ticket

**Comment by fauzanmursyid** [comment]
Ok, I have deleted the images
